### PR TITLE
Added Part-DB to Inventory section

### PR DESCRIPTION
**Pull request by jbtronics**
Added Part-DB (https://github.com/Part-DB/Part-DB) to inventory managment section.

For further infos about Part-DB see GitHub page, or the demo: http://part-db.bplaced.net/part-en/startup.php

### CODE REVIEW

**Comment by kasbah** [comment]
Thanks! Could you edit the descriptions of Partkeepr and Part-DB a bit to make it clearer what the difference is between the two?

**Comment by jbtronics** [comment]
The problem is, both softwares are very similar, because they has the same purpose...
They only differ in GUI and in some "detail" function (e.g. Part-DB has a permission system and better barcode generators... Partkeepr on the other hand has Parametric search and automatic datasheet import)...
I don't know how much i can/should go into details for the the descriptions for the list...

**Comment by kasbah** [comment]
Seems good to me:

- Open source web service for managing your part inventory with parametric search and automatic datasheet import
- Another open source web service for managing part inventory with a permission system and a good barcode generator

**Comment by jbtronics** [comment]
Ok, i put your ideas in the pull request

**Comment by kasbah** [comment]
Thanks!

**Pull request merged**
