### PR TITLE
Add Mr. Carlson's Lab to videos

### PR DESCRIPTION
**Pull request by MaggieLeber**
Can break this into two if you want. Also will understand if you don't want to link Rossman; he talks like a real Nooyawker. :-) Mr. Carlson is starting a tutorial series recently.

### CODE REVIEW

**Comment by kasbah** [comment]
Thanks for the PR, I have enjoyed Rossman's videos in the past and if accents were a concern then ElectroBOOM definitely wouldn't be on the list (Mooshay meter?). :laughing:   

There are _a lot_ of good youtube channels I am coming to realise though so I am not sure how big we should allow this section to get. Maybe we need to figure out some stronger guidelines on selecting channels. 

Rossman has quite a general appeal it seems and there is less electronic engineering involved (less theory covered etc. ). I wouldn't feel to bad about leaving it off. Does that sound right?

**Comment by MaggieLeber** [comment]
I think the value of Rossman is more seeing his microsoldering techniques and tooling choices; he doesn't much care about theory at all. And his accent isn't problematic, but his choice of words is...colorful. 

Maybe videos should break out into a separate MD file linked from the main readme. 

Your own judgement on Rossman, but not having Carlson would be a shame.

**Comment by kasbah** [comment]
Ah I see, let's hold off on Rossman for now but am happy to add Mr. Carlson.

**Comment by MaggieLeber** [comment]
Makes sense.

**Pull request merged**
